package exception_Handlings;

public class Array_exception {

	public static void main(String[] args) {
		System.out.println("mains starts");
		int a[]= {1,20,31,45,56};
		System.out.println(a[10]);
		System.out.println("main ends");

	}

}
